# Generated by Django 2.2.19 on 2023-09-08 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.IngredientIntermediate', to='recipes.Ingredient', verbose_name='Ингридиенты'),
        ),
    ]
