# Generated by Django 2.2.19 on 2023-09-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230905_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Cooking_time',
            field=models.IntegerField(verbose_name='Время приготовления'),
        ),
    ]
