# Generated by Django 2.2.19 on 2023-09-09 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230908_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientintermediate',
            name='amount',
            field=models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество 1!')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.IngredientIntermediate', to='recipes.Ingredient', verbose_name='Ингридиенты'),
        ),
    ]
