# Generated by Django 2.2.19 on 2023-09-10 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230909_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Cooking_time',
            new_name='cooking_time',
        ),
        migrations.AlterField(
            model_name='ingredientintermediate',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное количество 1!')], verbose_name='Количество'),
        ),
    ]
